apiVersion: v1
data:
    foo: ENC[AES256_GCM,data:O2jcUQ==,iv:FG6rj/a6j2ALXK/vmoIDO+XFFf/rW0XeDPiiennEBxo=,tag:WuhjiN1f1PFwG5t7AJ8a5g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: sopstest
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15983kn5u6hfel35332axhusgr28md0t9h2clauacelhlz9t40quqyykpn9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1WmM2VmMwMXVQVnNJRTZl
            Y283am4yV2VpK0JvWVh4RCtjcHNpU2FEblYwCmdkL2dqdXZuOWpJbWQ4Q3R1dG9p
            RDdNMEtxQllDTGNSeExoakt6eHBWd3MKLS0tIEpwcG83bjhCLy9kcERNYitRbE5C
            dVdDOGovRzVMSkxVMmpUUHZ0ODREeVUKGEzwsydLeZKPtzXztzkIsf+oOhz2D8Mm
            DoY6d6z8wyQEgXhcpkVHPOxiyt+cylLUwfPseb5Yo/DbctmO10qeOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-07T16:25:23Z"
    mac: ENC[AES256_GCM,data:QRA1CjO1cal0hFcDuTaAG5Q/YtJL6McN/SejvUY4BfsQBsPE1z00A0YxQlOlkK8d6UlDtt6fxDYjkElerE06edpkmE+Wx9js9JH1EK18MVixeH8FDXWGoYA2WD23ysPqJLft9C0YYdxCzQjOgnHIoQo9Xeb9FeUnDRRXdMkcwL4=,iv:GKrFMXB+5fB9IKCjlPqM40x5Ohwh470vGe7xwhOmREw=,tag:r6XUsIVktTj+AhChauZSvw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
