apiVersion: v1
data:
    foo: ENC[AES256_GCM,data:LMAltg==,iv:h+efqsTYvvfntQNL93SposK1bvCQOss50RYCBWYIXvM=,tag:EOVt7je5kC9CpF+6tkouqw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: sopstest
    namespace: monitoring
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15983kn5u6hfel35332axhusgr28md0t9h2clauacelhlz9t40quqyykpn9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMlZXdjVTYm81aERLV1pH
            RFlhN3VLVmR1K2JmOVExZmtZaGhxeXJlWXgwCi8rS3JBQ2t2dFRWSnF3eXRXeHV2
            QTBoQktQclo1c1BMTWlqNCtRNWdvdWcKLS0tIHZXMVRMUzBkRk9renBUYjJScXpZ
            ZkI1N3NPTm1OZkpocGpJTjllRGpUcEEKF28LmA301UbrSmhjpluWIOtEPeq8c25t
            uJVQ5FfOBIEPgSelmQq+UfSkSe/z+8HAPEVvgBEShwx+B/L7K76zBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-07T16:27:11Z"
    mac: ENC[AES256_GCM,data:3UdLA14Wn7qtJ1D/OzssLNhaC1+8Xoyhkkn7wvh6vh48g6H7UKSA9UbytPvxBUjZF87EQlaJ12WqfKZDKeqN6klIL76OxJ60CVPZ2/a5OiAeWY1e/ggaZlvHH2y6BjuCJDkagWn+eV4sMCdYcdvk5+zvM3ZTGPt29dnfBNIyLpY=,iv:fFUQ/gXvniFLXveWb9xStKt7Z3uNMbMDjxy63ODIlgk=,tag:zYbdT5UVA3fIpGM7AmKN/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
